services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/projet_cloud
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_SECURITY_USER_NAME: test
      SPRING_SECURITY_USER_PASSWORD: test
    depends_on:
      - db

  db:
    image: postgres:15.10
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: projet_cloud
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
